feat: allow secret parameter to be a function to support dynamic secrets
connorjburton/hmac-auth-express pull request #66
Opened 2021-08-22 13:33 UTC by connorjburton

2021-08-22 13:35 UTC, connorjburton commented
@neslisahgamze  Please review/try this branch and ensure it fits your needs. I still need to update documentation, version bump & changelog but it should be complete functionality wise.

2021-08-22 13:55 UTC, connorjburton commented
@Jimsalad Quick code review if you don't mind and have the time?

2021-08-23 07:55 UTC, neslisahgamze approved these changes

2021-08-23 08:01 UTC, neslisahgamze commented
> @neslisahgamze Please review/try this branch and ensure it fits your needs. I still need to update documentation, version bump & changelog but it should be complete functionality wise.

I checked this PR on my code and it works. Thank you 🎉

2021-08-23 20:43 UTC, Jimsalad commented on README.md
> +From [8.2.0](https://github.com/connorjburton/hmac-auth-express/releases/tag/v8.2.0) onwards you can supply a function as your `secret` parameter. This function accepts 1 parameter, being an `express
```suggestion
From [8.2.0](https://github.com/connorjburton/hmac-auth-express/releases/tag/v8.2.0) onwards you can alternatively supply a function as your `secret` parameter. This function accepts 1 parameter, being an `express.Request` object. This function can be `async`. You can use this feature to dynamically determine the secret of the request, for example if you have different HMAC secrets depending on the URL of the request.
```

2021-08-23 21:04 UTC, Jimsalad requested changes
Added a couple of nitpicks:

`index.ts` - return values from the `AuthError` return will not provide accurate `typeof` statements if certain data types such as `Promises` or `arrays` are passed in. This can be ignored if you're happy to stick with explicit JavaScript data structures.

`README.md` - proper nitpick, just changing some wording around what parameters you can provide.

Overall looks good though!

2021-08-23 21:04 UTC, james-salloway commented on src/index.ts
> +            return next(new AuthError(`Invalid secret. Expected non-empty string but got '${scopedSecret}' (type: ${typeof scopedSecret})`));
If you're concerned with `arrays` and `Promises` reporting correctly from the `typeof scopedSecret` error statement you will need to handle these independently - `arrays` will return as `object` and Promises will return as `function`.

2021-08-23 21:11 UTC, merged

2021-08-23 21:17 UTC, connorjburton commented
@neslisahgamze This is now released on NPM as `8.2.0`, thanks for your help.